version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/
hooks:
  BeforeInstall:
    - location: scripts/1-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/2-setup.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/3-startup.sh
      timeout: 300
